// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2pNBcXZvCl8z_lCvKbWHGkXkoyo81s4Q',
    appId: '1:1002346287390:web:95994ca71adeea9a6f390f',
    messagingSenderId: '1002346287390',
    projectId: 'kofauth-98ff2',
    authDomain: 'kofauth-98ff2.firebaseapp.com',
    storageBucket: 'kofauth-98ff2.appspot.com',
    measurementId: 'G-61Z0L29NP5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaBW0iAWnXnBZysDZ5g3JrBtBwIUWqS68',
    appId: '1:1002346287390:android:a0030ea12cf047cf6f390f',
    messagingSenderId: '1002346287390',
    projectId: 'kofauth-98ff2',
    storageBucket: 'kofauth-98ff2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4kVa-T3DyK6oj3UooVJZdSnpgadKFrzc',
    appId: '1:1002346287390:ios:c20435aabfc25f3f6f390f',
    messagingSenderId: '1002346287390',
    projectId: 'kofauth-98ff2',
    storageBucket: 'kofauth-98ff2.appspot.com',
    iosClientId: '1002346287390-m9sm3l4knlo1uudfp5tse7mhqnsla0qg.apps.googleusercontent.com',
    iosBundleId: 'com.example.kofAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4kVa-T3DyK6oj3UooVJZdSnpgadKFrzc',
    appId: '1:1002346287390:ios:5af935aae4b1b4536f390f',
    messagingSenderId: '1002346287390',
    projectId: 'kofauth-98ff2',
    storageBucket: 'kofauth-98ff2.appspot.com',
    iosClientId: '1002346287390-d7fddgqbkh9221k18kmsf7q915vfkpo4.apps.googleusercontent.com',
    iosBundleId: 'com.example.kofAuth.RunnerTests',
  );
}
